{{- if .Values.ghcr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ghcr.secretName }}
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.ghcr.username .Values.ghcr.token (printf "%s:%s" .Values.ghcr.username .Values.ghcr.token | b64enc) | b64enc }}
{{- end }}
