---
# Source: ping-pong/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    helm.sh/chart: ping-pong-0.1.0
    app.kubernetes.io/name: ping-pong
    app.kubernetes.io/instance: ping-pong
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiIiwicGFzc3dvcmQiOiIiLCJhdXRoIjoiT2c9PSJ9fX0=
