name: Reinstall PR Deployment

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to reinstall deployment for'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to deploy (leave empty to auto-detect latest PR image)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/bruj0/cicd-for-eks/ping-pong

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: ${{ inputs.image_tag || 'latest' }}
      build-type: 'development'
      branch-name: 'main'
      pr-number: ${{ inputs.pr_number }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  deployment-complete:
    runs-on: ubuntu-latest
    needs: deploy
    if: needs.deploy.result == 'success'
    steps:
    - name: Deployment summary
      run: |
        # Calculate deployment details
        PR_NUMBER="${{ inputs.pr_number }}"
        RELEASE_NAME="ping-pong-pr-${PR_NUMBER}"
        NAMESPACE="pr-${PR_NUMBER}"
        IMAGE_TAG="${{ inputs.image_tag || 'latest' }}"

        echo "## PR Deployment Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Successfully deployed PR #${{ inputs.pr_number }} to Kubernetes cluster." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        echo "### Deployment Details" >> $GITHUB_STEP_SUMMARY
        echo "- **PR:** #${{ inputs.pr_number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Release:** \`$RELEASE_NAME\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Namespace:** \`$NAMESPACE\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Image:** \`${{ env.IMAGE_NAME }}:${IMAGE_TAG}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        echo "### Management Commands" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "# Check deployment status" >> $GITHUB_STEP_SUMMARY
        echo "kubectl get pods -n $NAMESPACE" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "# View logs" >> $GITHUB_STEP_SUMMARY
        echo "kubectl logs -n $NAMESPACE -l app.kubernetes.io/name=ping-pong" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "# Uninstall deployment" >> $GITHUB_STEP_SUMMARY
        echo "helm uninstall $RELEASE_NAME --namespace $NAMESPACE" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
