name: Test Application

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up cache for pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up cache for pre-commit
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('src/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        # Install pre-commit hooks
        pre-commit install

        # Run all pre-commit hooks
        pre-commit run --all-files

    - name: Run pytest unit tests
      working-directory: ./src
      run: |
        echo "Running pytest unit tests..."
        python -m pytest test_main.py -v --tb=short
        echo "All unit tests passed!"

    - name: Test Summary
      run: |
        echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Pre-commit Hooks**: All code quality checks passed" >> $GITHUB_STEP_SUMMARY
        echo "**Unit Tests**: All pytest tests passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Ready for deployment!**" >> $GITHUB_STEP_SUMMARY
